<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQzMJZVQ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQzMJZVQ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQzMJZVQ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQzMJZVQ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQzMJZVQ\App_KernelProdContainer([
    'container.build_hash' => 'QzMJZVQ',
    'container.build_id' => 'b54d7fa5',
    'container.build_time' => 1744190300,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQzMJZVQ');
